version: '3.1'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPsw
      - POSTGRES_DB=testDB
    ports:
      - "5432:5432"